name: Deploy to staging

on:
  push:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Deploy to server (staging)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.STAGING_SSHKEY }}
          script: deploy-branch-staging.sh
